// <auto-generated />
namespace EF_Migration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Forth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Forth));
        
        string IMigrationMetadata.Id
        {
            get { return "202004161233492_Forth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
